# Generated by Django 3.2.13 on 2022-05-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewallapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tittle',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
