# Generated by Django 3.2.13 on 2022-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewallapi', '0002_auto_20220512_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
