# Generated by Django 3.2.13 on 2022-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewallapi', '0002_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
